packages:
  - "packages/*"
  - "libs/tokens"
  - "libs/migration-data"
  - "libs/ui-kit"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  unrs-resolver: true
