/// <reference lib="dom" />
import type { Decorator, Preview } from '@storybook/angular';
import { applicationConfig } from '@storybook/angular';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { providePrimeNG } from 'primeng/config';
import { usePreset } from '@primeuix/themes';
import { addons } from 'storybook/internal/preview-api';
import { DARK_MODE_EVENT_NAME } from 'storybook-dark-mode';
import { MyBky, Sampark, withAccent, withPrimaryRamp, withSurface, applyThemeToDesignSystem, rampFor } from '@org/ui-kit';



// Compodoc metadata for the API tables. The storybook target regenerates
// documentation.json on every start (compodoc: true + compodocArgs in
// apps/storybook-host/project.json); generating it is NOT enough on its own -
// the framework only reads it once it is registered here, which is why the
// ArgTypes tables were showing only the args each story meta declared by hand.
// The path is relative because documentation.json is generated build output at
// the workspace root, not a library — there is no alias to import it through.
// eslint-disable-next-line @nx/enforce-module-boundaries
import docJson from '../../../documentation.json';
import { setCompodocJson } from '@storybook/addon-docs/angular';

setCompodocJson(docJson);

// ── Keep implementation internals out of the Controls panel ────────────────
//
// Compodoc documents every PUBLIC class member, and Storybook turns each one
// into a Controls row. For a ControlValueAccessor that means `writeValue`,
// `registerOnChange`, `registerOnTouched`, `setDisabledState` and the internal
// `value` field all appear as controls — as do computed getters like `dt`,
// `resolvedPanelStyleClass` and `panelClass`, and imperative methods like
// `toggle`, `open`, `close`, `apply`.
//
// Measured: 137 distinct non-input members across the library. On
// `baps-slider` that was 17 placeholder rows against 7 real controls, so the
// panel read as a list of "Set object" buttons rather than something a reader
// could drive.
//
// Derived here rather than hand-listed, for two reasons: 137 names is not
// maintainable by hand, and the list has to stay correct as components change.
// docJson is regenerated by compodoc on every Storybook start, so this is
// always in step with the source.
//
// The subtraction matters. A name is only excluded if it is an @Input or
// @Output on NO component — `value` is a real input on some components and a
// CVA field on others, and excluding it globally would hide a control people
// need.
const declaredIO = new Set<string>();
const otherMembers = new Set<string>();

for (const component of (docJson as { components?: unknown[] }).components ?? []) {
  const c = component as {
    inputsClass?: { name: string }[];
    outputsClass?: { name: string }[];
    propertiesClass?: { name: string }[];
    methodsClass?: { name: string }[];
    accessors?: Record<string, unknown>;
  };
  for (const i of c.inputsClass ?? []) declaredIO.add(i.name);
  for (const o of c.outputsClass ?? []) declaredIO.add(o.name);
  for (const p of c.propertiesClass ?? []) otherMembers.add(p.name);
  for (const m of c.methodsClass ?? []) otherMembers.add(m.name);
  for (const a of Object.keys(c.accessors ?? {})) otherMembers.add(a);
}

const CONTROLS_EXCLUDE = [...otherMembers].filter((name) => !declaredIO.has(name));

import 'primeicons/primeicons.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
// eslint-disable-next-line @nx/enforce-module-boundaries
import '../../../libs/tokens/build/css/tokens.css';
// Global app styles: fonts, rem baseline, and the input skins
// (components/input/_input.scss + _input-sampark.scss). Imported here rather
// than via the storybook target's `styles` option — see the .scss rule in
// main.ts for why that option doesn't work in this workspace.
import '../src/styles.scss';

// PrimeNG hardcodes `.p-button { font-size: 1rem }` in its base stylesheet —
// .p-button-sm/.p-button-lg DO consume definePreset tokens, but the unsized
// default does not, so it can't be fixed via baps.theme.ts alone. Figma node
// 22465:93605 specifies 14px for the default (M) size. Injected directly
// (rather than via a .css import) since cross-package CSS imports from
// .storybook/preview.ts were not reliably reaching the bundle here.
if (typeof document !== 'undefined') {
  const style = document.createElement('style');
  style.textContent = `
    .p-button:not(.p-button-sm):not(.p-button-lg) { font-size: 14px; }
  `;
  document.head.appendChild(style);

  // The docs-shell chrome (dark-mode surfaces, prose, code blocks, arg
  // tables, page rhythm, syntax colours) used to be injected here as two
  // more <style> blocks. It now lives in ../src/_docs-shell.scss, imported
  // through ../src/styles.scss above, so the values come from a token tier
  // instead of literals and the rules no longer name the mode.


  // storybook-dark-mode only toggles its class on the MANAGER body — the preview
  // iframe never receives it, so PrimeNG's darkModeSelector ('.baps-dark') and the
  // docs dark rules above never activate and the inner content stays light while
  // the chrome flips. Bridge the addon's channel event into the iframe: mirror
  // .baps-dark / .baps-light onto the iframe body so the whole preview + docs page
  // switches with the toolbar toggle. Initial state comes from the addon's own
  // persisted store (STORAGE_KEY 'sb-addon-themes-3') so a freshly-loaded docs
  // iframe isn't stuck light until the first event arrives.
  const setDark = (isDark: boolean) => {
    document.body.classList.toggle('baps-dark', isDark);
    document.body.classList.toggle('baps-light', !isDark);
  };
  let initialDark = false;
  try {
    initialDark = JSON.parse(localStorage.getItem('sb-addon-themes-3') ?? '{}').current === 'dark';
  } catch {
    /* no persisted mode yet — default to light */
  }
  setDark(initialDark);
  addons.getChannel().on(DARK_MODE_EVENT_NAME, setDark);

  // Hide PrimeNG overlay masks (drawer, dialog, …) on the merged Docs page
  // only — matching PrimeNG's own reference docs (primeng.dev), where
  // opening a demo's drawer never dims the surrounding page at all. PrimeNG
  // always appends its mask (`position: fixed`, class `p-drawer-mask`/
  // `p-dialog-mask`/…) to `document.body` regardless of any `appendTo`
  // input — see baps-drawer's own doc comment — and it is never a DOM
  // descendant of `.docs-story`, so no CSS containment rule can reach it.
  // Transparent rather than removed/reparented: PrimeNG's own close logic
  // still finds it exactly where it left it (`document.body.removeChild`,
  // which throws if the node moved parents in the meantime) and the click
  // catcher backing "dismiss on backdrop click" still works.
  //
  // A standalone story canvas (Playground, Open, …) has no `.docs-story` on
  // the page at all, so `document.querySelector` below returns null and the
  // mask is left alone — a real dim there is correct, matching production.
  new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      for (const node of mutation.addedNodes) {
        if (!(node instanceof HTMLElement) || !node.className.includes('-mask')) continue;
        if (!document.querySelector('.docs-story')) continue;
        node.style.background = 'transparent';
      }
    }
  }).observe(document.body, { childList: true });
}

// Applies the design system chosen in the toolbar ("Design system" dropdown):
// - provides the selected preset to providePrimeNG so every (re)bootstrap —
//   Storybook re-bootstraps the Angular app on story navigation — starts on
//   the right theme, with no flash of the wrong preset
// - calls usePreset() for live toolbar switches, since PrimeNG's theme is a
//   document-level singleton and a running app won't re-read its providers
// - toggles the .baps-ds-sampark body class, which scopes the extra CSS that
//   PrimeNG tokens can't express (e.g. Sampark button heights)
// Named MyBky, not Baps: the preset is the MyBKY skin and always was. The old
// `Baps` name survives as a deprecated alias for the two consuming apps.
const DS_PRESETS = { mybky: MyBky, sampark: Sampark };
let activePreset: string | undefined;

// ── One ramp, two sinks ─────────────────────────────────────────────────────
//
// Picking a primary swatch used to re-theme HALF the preview. `usePreset()`
// moves everything painted from PrimeNG's `--p-*`, and the design system paints
// a great deal from its OWN tokens — 23 of them reference a MyBKY blue step.
// Measured before this existed: at `accent:rose`, `--p-primary-color` went to
// #cf3650 while `--color-mybky-blue-600` stayed #5f78b8, and a primary tag
// rendered entirely blue (bg #eef0f8, border #9fadd9@20%, text #384871) against
// rose buttons.
//
// So the same ramp now feeds both: `withAccent` hands it to PrimeNG, and this
// writes it onto the design system's own custom properties. `PRIMARY_RAMPS` is
// read rather than re-derived, because the four BAPS accents are hand-authored
// token ramps and `palette(swatch.color)` would produce different values for
// them — two ramps, and the drift would be invisible.
//
// The derived tokens follow for free: `--color-mybky-blue-alpha10` is
// `rgb(from var(--color-mybky-blue-600) r g b / 0.1)`, so it re-tints itself.

// ── Scaffolded brands ───────────────────────────────────────────────────────
//
// BAPS default and App Sell are in the switcher but have no palette. They are
// listed rather than hidden so the intended set is visible and adding a palette
// is a data change, not a feature.
//
// Selecting one does NOT skin the preview. Guessing — falling back to MyBKY
// silently, or dropping to raw Material — produces a page that looks like a
// brand and is not one, and someone eventually screenshots it as if it were.
// The preview stays on the MyBKY base and says why, which is honest and
// reversible the moment the colours arrive.
const AWAITING_PALETTE: Record<string, string> = {
  baps: 'BAPS default',
  appsell: 'App Sell',
};

const NOTICE_ID = 'baps-awaiting-palette';
const NOTICE_STYLE_ID = 'baps-awaiting-palette-style';

// A stylesheet rather than an inline style, so dark mode can override it.
// storybook-dark-mode toggles `.baps-dark` on the body AFTER this element is
// created, and an inline style would outrank any later rule — the notice would
// stay a white box on a dark page.
const NOTICE_CSS = `
#${NOTICE_ID} {
  position: fixed;
  inset: auto 12px 12px auto;
  z-index: 2147483647;
  max-width: 22rem;
  padding: 10px 14px;
  border: 1px solid #e4ecf1;
  border-radius: 8px;
  background: #fff;
  box-shadow: 0 4px 14px rgba(16, 24, 40, 0.12);
  font: 400 13px/1.5 Inter, system-ui, sans-serif;
  color: #2b2f32;
}
.baps-dark #${NOTICE_ID} {
  border-color: #2b3033;
  background: #1b1f22;
  color: #f4f6f7;
  box-shadow: 0 4px 14px rgba(0, 0, 0, 0.4);
}
@media (prefers-reduced-motion: reduce) {
  #${NOTICE_ID} { transition: none; }
}
`;

const showAwaitingPaletteNotice = (label: string | undefined): void => {
  if (typeof document === 'undefined') return;
  const existing = document.getElementById(NOTICE_ID);

  if (!label) {
    existing?.remove();
    return;
  }

  if (!document.getElementById(NOTICE_STYLE_ID)) {
    const style = document.createElement('style');
    style.id = NOTICE_STYLE_ID;
    style.textContent = NOTICE_CSS;
    document.head.appendChild(style);
  }

  const el = existing ?? document.createElement('div');
  if (!existing) {
    el.id = NOTICE_ID;
    // Announced, because a colour-only signal is no signal for a screen reader
    // and this is the difference between "themed" and "not themed yet".
    el.setAttribute('role', 'status');
    // On <body>, deliberately outside #storybook-root: the visual baseline
    // screenshots the root, so this can never leak into a snapshot even if a
    // scaffold were somehow selected during a run.
    document.body.appendChild(el);
  }
  el.textContent = `${label} has no palette yet — the preview is showing the MyBKY base, unskinned for this brand.`;
};

/**
 * The design-system ramp each brand exposes, and where a `palette()` step goes.
 *
 * MyBKY shares `palette()`'s own 50–950 shape, so every step maps to itself and
 * the write is exact.
 *
 * Sampark declares 0/10/20/40/60/80/100 — a different scale. The pairs below
 * are the INVERSE of the preset's own primitive map (`sampark.theme.ts`, the
 * `samparkMaroon` block), which already declares where each Sampark step sits
 * on PrimeNG's 50–950 scale:
 *
 *   samparkMaroon.500 = Primary60   .600 = Primary60   .700 = Primary80
 *   samparkMaroon.800 = Primary100  .900 = Primary100  .950 = Primary100
 *
 * That map, not a colour measurement, is the right authority — and getting this
 * wrong once is why the reasoning is written down.
 *
 * The first attempt derived the map by matching each Sampark step against
 * `palette('#c96868')` by RGB distance and luminance, and picked 60→500,
 * 80→600. Measured, and wrong. PrimeNG's `semantic.colorScheme.light.primary`
 * reads `{primary.600}` / `{primary.700}` / `{primary.800}`, so under an accent
 * PrimeNG landed on palette 600 while the design system wrote palette 500 into
 * `primary-60` — two different reds on one page (`#cf3650` against `#f43f5e`).
 *
 * Colour distance was measuring the wrong thing. At the default nothing is
 * written at all (see the guard below), so the Figma values apply exactly either
 * way; under an accent the whole ramp is a different hue and there is no Figma
 * value left to be close to. The only property that shows on screen is whether
 * the two sinks pick the SAME step. This map guarantees that by construction.
 *
 * It does make the distance-to-Figma worse — total Δ 100 -> 145, with 60 going
 * Δ0 -> Δ38 and 80 Δ34 -> Δ41. That number is not worth optimising, for the
 * reason above.
 *
 * palette 300/900/950 have no Sampark counterpart and are not written; 500 is
 * skipped because the preset collapses 500 and 600 onto the same step and 600 is
 * the one `primary.color` actually reads.
 *
 * DS_RAMPS, rampFor and applyThemeToDesignSystem now live in @org/ui-kit
 * (accent.theme.ts) so apps get the same sink Storybook uses; imported above.
 */


const withDesignSystem: Decorator = (storyFn, context) => {
  const selected = String(context.globals['designSystem'] ?? 'mybky');
  // A scaffolded brand falls back to the MyBKY base and announces itself; it
  // never borrows another brand's skin. Anything unrecognised lands here too,
  // which is the right default for a stale URL carrying a removed brand.
  const awaiting = AWAITING_PALETTE[selected];
  showAwaitingPaletteNotice(awaiting);
  const ds: keyof typeof DS_PRESETS = selected === 'sampark' ? 'sampark' : 'mybky';
  const accent = (context.globals['accent'] as string) ?? 'brand';
  const surface = (context.globals['surface'] as string) ?? 'default';
  const ripple = context.globals['ripple'] !== false;
  // A swatch key goes through the library's own `withAccent`; a raw hex from the
  // builder is applied here instead, because `withAccent` resolves its argument
  // against `PRIMARY_RAMPS` and a hex is not a key there. Same shape either way —
  // `semantic.primary` replaced with a ramp — so the library needs no change.
  const accentRamp = accent.startsWith('#') ? rampFor(accent) : undefined;
  const branded = accentRamp
    ? // `withPrimaryRamp`, not a bare `semantic.primary` merge: the library
      // function also remaps the primary-derived `components.*` entries, which
      // is what makes the MyBKY button fill follow the accent. Merging only
      // `semantic.primary` here would have left the theme builder's own hex
      // moving the surfaces while the primary button kept its baked gradient —
      // the exact bug Route A fixes, reintroduced on the one path that bypasses
      // `withAccent`.
      withPrimaryRamp(DS_PRESETS[ds], accentRamp)
    : withAccent(DS_PRESETS[ds], accent);
  const preset = withSurface(branded, surface);
  if (typeof document !== 'undefined') {
    document.body.classList.toggle('baps-ds-sampark', ds === 'sampark');
    // Also on <html>. preview-head.html adds it there from the URL so the first
    // painted frame is already the right brand; without this line a LIVE switch
    // (which re-renders without reloading the iframe) would leave that initial
    // class behind and the two elements would disagree. The docs-page brand CSS
    // keys off the class as an ancestor, so a stale one on <html> would show the
    // wrong brand's prose.
    document.documentElement.classList.toggle('baps-ds-sampark', ds === 'sampark');
    // Comparison blocks on docs pages read this, the same way the sidebar
    // filter reads the `comparison` global — see BrandOnly in .storybook/blocks.
    document.body.dataset['bapsComparison'] =
      context.globals['comparison'] === true ? 'on' : 'off';
    // RTL global, driven by the Theme settings popover (see manager.tsx). Dark
    // mode is NOT handled here — storybook-dark-mode owns the `.baps-dark` class
    // (PrimeNG's darkModeSelector, configured below) across chrome + preview.
    document.documentElement.dir = context.globals['direction'] === 'rtl' ? 'rtl' : 'ltr';
  }
  // The design-system sink. Runs on every render, not only on change, because
  // Storybook re-bootstraps the Angular app on story navigation and the inline
  // properties have to survive that. It is idempotent and a no-op at the
  // default, so re-running it costs nothing.
  applyThemeToDesignSystem(ds, accent);

  // PrimeNG's theme is a document-level singleton — a running app won't re-read
  // its providers, so push preset changes (design system / primary / surface) live.
  const presetKey = `${ds}:${accent}:${surface}`;
  if (activePreset !== undefined && presetKey !== activePreset) {
    usePreset(preset);
  }
  activePreset = presetKey;
  return applicationConfig({
    providers: [
      provideAnimationsAsync(),
      providePrimeNG({
        ripple,
        theme: {
          preset,
          options: {
            darkModeSelector: '.baps-dark',
            cssLayer: {
              name: 'primeng',
              order: 'theme, base, components, primeng, utilities, app-styles',
            },
          },
        },
      }),
    ],
  })(storyFn, context);
};

const preview: Preview = {
  globalTypes: {
    designSystem: {
      description: 'Source project whose design system skins the preview',
      toolbar: {
        title: 'Design system',
        icon: 'paintbrush',
        items: [
          { value: 'mybky', title: 'MyBKY (events-ui)' },
          { value: 'sampark', title: 'Sampark (spm-ui)' },
          // Scaffolds. Present so the switcher shows the full intended set and
          // the shape of the work is visible, but they have no palette yet —
          // selecting one says so rather than rendering a guess. See
          // AWAITING_PALETTE.
          { value: 'baps', title: 'BAPS default — awaiting palette' },
          { value: 'appsell', title: 'App Sell — awaiting palette' },
        ],
        dynamicTitle: true,
      },
    },
  },
  initialGlobals: {
    designSystem: 'mybky',
    accent: 'brand',
    surface: 'default',
    ripple: true,
    direction: 'ltr',
    // Off by default — see BrandFilter in manager.tsx. Declared here so the
    // global exists from the first render rather than appearing on first toggle.
    comparison: false,
  },
  parameters: {
    // ── Actions: why there is NO argTypesRegex here ──────────────────────
    //
    // `actions: { argTypesRegex: … }` is the usual one-line way to make every
    // output log itself, and it is the wrong tool for an Angular wrapper
    // library. It was tried, measured, and removed.
    //
    // Storybook applies args to an Angular component by ASSIGNING them onto the
    // instance. For an @Output that means the arg's spy REPLACES the real
    // EventEmitter rather than subscribing to it — so any output whose name the
    // regex matched stopped emitting to whatever the wrapper's own template had
    // bound it to. Five interaction stories went from passing to failing:
    // drawer and popover would not open, pagination would not change page,
    // users-dropdown would not fill its panel. Nothing in the rendered output
    // hinted at the cause; the components simply stopped responding.
    //
    // Narrowing the pattern does not save it. The names that break are exactly
    // the useful ones — `visibleChange` is the write-back half of
    // `[(visible)]`, and `page`, `show`, `close`, `hidden` are what these
    // wrappers bind internally. A regex tight enough to be safe matches almost
    // nothing worth logging.
    //
    // Actions still work, through the pattern the passing stories already use:
    // bind the output in the TEMPLATE to a spy declared in args.
    //
    //     args: { onSelected: fn() },
    //     render: (args) => ({
    //       props: args,
    //       template: '<baps-file-upload (filesSelected)="onSelected($event)" />',
    //     }),
    //
    // More verbose, and better on two counts: the real emitter stays intact,
    // and the snippet in Show code names the event a consumer has to handle
    // instead of hiding it behind a global regex.

    // ── Accessibility ────────────────────────────────────────────────────
    //
    // addon-a11y runs axe on every story. This block turns OFF exactly one
    // rule, and the reason matters more than the setting.
    //
    // `color-contrast` fires on 107 nodes across 19 of 51 components — every
    // placeholder, every muted helper line, every disabled control. It is not
    // 19 separate mistakes: they all resolve to the same handful of Sampark and
    // MyBKY neutral tokens, so it is ONE system-level decision about the
    // palette, taken by design, not something a story can fix.
    //
    // Turning it off here rather than per story is the honest shape: a
    // per-story override would imply each one is a local exception being
    // reviewed, when in fact none of them can be resolved without changing
    // tokens — and tokens are out of scope for a Storybook pass. Every other
    // axe rule stays on, and the ones that DID surface real problems were
    // fixed (missing accessible names on multi-select, slider and the
    // accordion's hosted controls) or recorded as component-level findings.
    //
    // The full list, and what it would take to clear it, is written up in
    // Guidelines/Accessibility. Re-enable this rule the day the neutral ramp
    // is revisited — the violations are still there, just not gating.
    a11y: {
      config: {
        rules: [{ id: 'color-contrast', enabled: false }],
      },
    },


    // storybook-dark-mode v4 reads its settings from THIS parameter, not from
    // addons.setConfig in manager.tsx — a darkMode block there is ignored, which
    // is why the chrome used to fall back to Storybook's stock dark theme while
    // only the preview flipped.
    darkMode: {
      // `dark`/`light` are deliberately ABSENT.
      //
      // storybook-dark-mode re-applies its theme on STORY_CHANGED,
      // SET_STORIES and DOCS_RENDERED — not just on mount — and a theme given
      // here always overwrites the persisted one. With the MyBKY pair pinned
      // here, every navigation stamped MyBKY back over a Sampark chrome, and
      // no amount of re-applying from the manager could win the race.
      //
      // Omitted, the addon falls back to its PERSISTED store, which
      // manager.tsx's ThemeSync keeps pointed at the selected brand. The addon
      // stays the only thing that applies a theme; the brand is just chosen
      // somewhere it can actually see.
      // The classes PrimeNG's darkModeSelector and the docs shell key off.
      darkClass: 'baps-dark',
      lightClass: 'baps-light',
      classTarget: 'body',
      stylePreview: true,
    },
    options: {
      // Deterministic sidebar order. Without a storySort the tree follows story
      // DISCOVERY order, which is filesystem-dependent and differs between a
      // dev server and a static build.
      //
      // Nested arrays order the children of the entry before them; anything not
      // named falls back to alphabetical, so a new component appears in its
      // category without this list needing an edit.
      storySort: {
        method: 'alphabetical',
        order: [
          'Getting Started',
          'Foundations',
          'Components',
          // Atomic Design, smallest first. Every component meta pins its own
          // id, so these are SIDEBAR LABELS only — the story URLs, and the 462
          // visual baselines keyed off them, did not move.
          //
          // Atoms and Molecules are the two atomic tiers this library actually
          // has. Organisms is the third bucket rather than a promise: the ten
          // components in it (Table, Tree Table, Dialog, Drawer, Navbar,
          // Internal Navbar, Toolbar, Stepper, and the two Table *Config
          // drawers) are page SECTIONS, not reusable units, and forcing them
          // into Molecules would have made Molecules mean nothing. Patterns,
          // Guidelines and Docs stay outside Components entirely.
          ['Atoms', 'Molecules', 'Organisms'],
          'Patterns',
          'Guidelines',
          'Docs',
        ],
        locales: 'en-US',
      },
    },
    controls: {
      // A colour-named or Date-named arg gets a real picker rather than a text
      // box, so a reader can discover the valid values from the control itself.
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },

      // Inputs and outputs only — CONTROLS_EXCLUDE is derived at the top of
      // this file from compodoc's own member list. Without it the panel filled
      // with implementation internals: on baps-slider, 17 placeholder rows
      // (writeValue, registerOnChange, setDisabledState, percent, …) against 7
      // real controls, which reads as a list of "Set object" buttons rather
      // than something anyone can drive.
      exclude: CONTROLS_EXCLUDE,

      // Type and description beside every control, so the panel is readable
      // without opening the Docs page. Compodoc supplies both, so this is free.
      expanded: true,

      // Required inputs first — the ones a consumer cannot omit.
      sort: 'requiredFirst',
    },
    docs: {
      // Right-hand "On this page" nav, off by default in Storybook 8.
      //
      // The component pages are now mostly examples — one section per story —
      // so the page is only navigable if that list is on screen. h2 gives the
      // top level (Usage / Examples / Forms / Accessibility) and h3 nests each
      // example under it, which is the shape primeng.dev uses.
      toc: {
        headingSelector: 'h2, h3',
        // A story is free to use headings in its own template — the typography
        // showcase does — and without this they are collected as PAGE sections,
        // so the nav fills up with 'The quick brown fox jumps over the lazy dog'.
        // Only the MDX's own headings are page structure.
        ignoreSelector: '.docs-story *',
        title: 'On this page',
      },
      // ── Make "Show code" paste-ready ──────────────────────────────────────
      //
      // A story binds its inputs to args so the Controls panel can drive them:
      //
      //     <baps-file-upload [brand]="brand" [hint]="hint" ... />
      //
      // That is correct FOR THE STORY and wrong for a reader, because the code
      // block is the thing people copy. Pasted into an app, every one of those
      // reads as "the property brand on MY component", and Angular fails the
      // build with TS2339 / NG8002. Worse, a failed build makes the dev server
      // keep serving the last good bundle, so the page does not show an error —
      // it just stops changing, and the reader has no idea the paste was the
      // cause. Measured: it cost one reader six build failures in a row.
      //
      // So the emitted snippet is rewritten to the CONCRETE values the story is
      // rendering, which is what primeng.dev's own docs show. The DOM is
      // untouched — this only changes the text of the code block.
      //
      // `brand` is dropped rather than inlined: the toolbar's Design system
      // toggle scopes the whole page, and an app is normally single-brand and
      // relies on that same scope, so a hard-coded brand on every element is
      // noise a reader would have to strip anyway. Per-instance `brand` stays
      // wherever a story wrote it as a literal, which is exactly the case the
      // input exists for.
      source: {
        transform: (code: string, ctx: { args?: Record<string, unknown> }) => {
          const args = ctx?.args ?? {};
          let out = code;

          // [input]="argName" -> input="value" / [input]="true" / dropped.
          out = out.replace(
            /\[([\w.$]+)\]="([A-Za-z_$][\w$]*)"/g,
            (whole, input: string, expr: string) => {
              // `brand` goes first and unconditionally. It used to be dropped
              // only when the story supplied it as an arg, which held while
              // every meta carried `brand: 'mybky'`. Those args were removed as
              // dead — dead for RENDERING, since a mybky pin cannot beat the
              // page scope — and the snippets then started showing a raw
              // `[brand]="brand"` binding. The brand comes from the page scope,
              // so it is noise in a copied snippet either way.
              if (input === 'brand') return '';
              if (!Object.prototype.hasOwnProperty.call(args, expr)) return whole;
              const value = args[expr];
              if (value === undefined || value === null) return '';
              if (typeof value === 'string') return input + '="' + value + '"';
              if (typeof value === 'number' || typeof value === 'boolean') {
                return '[' + input + ']="' + String(value) + '"';
              }
              // Objects and arrays stay as a binding — a reader has to supply
              // the data, and inlining a serialised array would be worse than
              // the name of the thing they need.
              return whole;
            },
          );

          // A dropped attribute leaves trailing spaces and can empty a line.
          out = out.replace(/[ \t]+$/gm, '').replace(/\n{3,}/g, '\n\n');
          return out;
        },
      },
    },
  },
  decorators: [withDesignSystem],
};

export default preview;
